# Generated by Django 3.2.19 on 2023-06-15 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer_profiler_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='age',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='country',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='name',
        ),
        migrations.AddField(
            model_name='coach',
            name='cricketer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cricketer_profiler_app.cricketer'),
            preserve_default=False,
        ),
    ]
