# Generated by Django 3.2.19 on 2023-06-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer_profiler_app', '0002_auto_20230615_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachTeam',
        ),
    ]
