# Generated by Django 3.2.19 on 2023-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer_profiler_app', '0004_cricketer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_format',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
