# Generated by Django 3.2.19 on 2023-06-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer_profiler_app', '0005_team_team_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketer_profiler_app.matchformat'),
        ),
    ]
