# Generated by Django 3.2.19 on 2023-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer_profiler_app', '0006_alter_team_team_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
