# Generated by Django 3.2.19 on 2023-06-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer_profiler_app', '0007_team_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_winner',
            new_name='winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_1_batting_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_1_bowling_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2_batting_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2_bowling_score',
        ),
        migrations.AddField(
            model_name='match',
            name='win_by_runs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='win_by_wickets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
