# Generated by Django 3.2.19 on 2023-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer_profiler_app', '0008_auto_20230617_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
